# Generated by Django 5.2.1 on 2025-06-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('all', 'Hammasi'), ('world', 'Dunyo sayohati'), ('ocean', 'Okean sayohati'), ('summer', 'Yozgi sayohat'), ('sport', 'Sport sayohati')], default='all', max_length=20)),
                ('title', models.CharField(default='Sayohat', max_length=100)),
                ('lightbox_group', models.CharField(default='gallery', max_length=50)),
            ],
        ),
    ]
