# Generated by Django 5.2.1 on 2025-06-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('all', 'Hammasi'), ('historical', 'Tarixiy joylar'), ('nature', 'Tabiat go‘zalliklari'), ('mountain', 'Tog‘ sayohatlari'), ('desert', 'Cho‘l safari')], default='all', max_length=20),
        ),
    ]
