# Generated by Django 5.2.1 on 2025-06-01 07:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_galleryitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('date_time', models.DateTimeField(verbose_name='Sana va vaqt')),
                ('persons', models.PositiveIntegerField(verbose_name='Nechta kishi')),
                ('category', models.CharField(choices=[('family', 'Oila'), ('individual', 'Yakka'), ('group', 'Guruh'), ('kids', 'Bolalar')], max_length=20, verbose_name='Toifa')),
                ('message', models.TextField(blank=True, verbose_name='Maxsus iltimos')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.package', verbose_name="Sayohat yo'nalishi")),
            ],
        ),
    ]
