# Generated by Django 5.2.1 on 2025-06-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('mavzu', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('xabar', models.TextField(verbose_name='Xabar')),
                ('sana', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
            ],
            options={
                'verbose_name': 'Kontakt xabar',
                'verbose_name_plural': 'Kontakt xabarlari',
            },
        ),
    ]
